# Generated by Django 3.2.7 on 2021-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locationId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
