# Generated by Django 3.2.7 on 2021-11-01 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_locationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
