# Generated by Django 3.2.7 on 2021-11-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
