# Generated by Django 3.2.9 on 2021-11-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211115_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numberOfPlayers',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
