# Generated by Django 3.2.9 on 2021-11-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_numberofplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='numberOfPlayers',
            field=models.PositiveIntegerField(verbose_name='Number of People Needed:'),
        ),
    ]
