# Generated by Django 3.2.7 on 2021-11-16 22:29

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_numberofplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[events.models.Event.no_past], verbose_name='Event Date'),
        ),
    ]
