language:
- python
python:
- 3.7

before-install:
  - pip3 install -r requirements.txt

script:
- python manage.py makemigrations
- python manage.py migrate
- black .
- flake8 --max-line-length=100
- python3 manage.py collectstatic --no-input
- coverage run --source="." manage.py test
after_script:
- coveralls
