# Generated by Django 3.2.7 on 2021-11-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noshow',
            old_name='user',
            new_name='owner',
        ),
    ]
