# Generated by Django 3.2.7 on 2021-11-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_rename_user_noshow_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misbehavior',
            old_name='user',
            new_name='owner',
        ),
    ]
