# Generated by Django 3.2.7 on 2021-11-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_rename_user_misbehavior_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misbehavior',
            old_name='owner',
            new_name='user',
        ),
    ]
