# Generated by Django 3.2.7 on 2021-11-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('select', 'SELECT'), ('manhattan', 'MANHATTAN'), ('queens', 'QUEENS'), ('bronx', 'BRONX'), ('brooklyn', 'BROOKLYN'), ('staten_island', 'STATEN ISLAND')], default='select', max_length=20),
        ),
    ]
