# Generated by Django 3.2.7 on 2021-11-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20211121_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='track',
        ),
    ]
