# Generated by Django 3.2.7 on 2021-11-09 01:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20211108_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borough',
        ),
        migrations.AlterField(
            model_name='profile',
            name='distance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('select', 'SELECT'), ('manhattan', 'MANHATTAN'), ('queens', 'QUEENS'), ('bronx', 'BRONX'), ('brooklyn', 'BROOKLYN'), ('staten_island', 'STATEN ISLAND')], max_length=52),
        ),
    ]
