# Generated by Django 3.2.7 on 2021-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20211123_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='baseball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='football',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='softball',
            field=models.BooleanField(default=False),
        ),
    ]
