# Generated by Django 3.2.7 on 2021-11-09 01:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20211108_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='distance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('select', 'SELECT'), ('manhattan', 'MANHATTAN'), ('queens', 'QUEENS'), ('bronx', 'BRONX'), ('brooklyn', 'BROOKLYN'), ('staten_island', 'STATEN ISLAND')], default=None, max_length=52),
        ),
    ]
