# Generated by Django 3.2.9 on 2021-11-24 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20211122_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adultBaseball',
            new_name='baseball',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adultFootball',
            new_name='football',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adultSoftball',
            new_name='softball',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='littleLeagueBaseball',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='littleLeagueSoftball',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tBall',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youthFootball',
        ),
    ]
