# Generated by Django 3.2.7 on 2021-11-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_alter_profile_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car',
            field=models.CharField(choices=[('select', 'SELECT'), ('yes', 'YES'), ('no', 'NO')], default='select', max_length=10),
        ),
    ]
