# Generated by Django 3.2.7 on 2021-11-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_profile_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='youthFootball',
            field=models.BooleanField(default=False, verbose_name='Youth Football'),
        ),
    ]
