# Generated by Django 3.2.7 on 2021-11-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_profile_youthfootball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('select', 'SELECT'), ('manhattan', 'MANHATTAN'), ('queens', 'QUEENS'), ('bronx', 'BRONX'), ('brooklyn', 'BROOKLYN'), ('staten_island', 'STATEN ISLAND')], default='select', max_length=20, verbose_name='Borough'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youthFootball',
            field=models.BooleanField(default=False),
        ),
    ]
