# Generated by Django 3.2.7 on 2021-11-09 02:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20211108_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='distance',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('manhattan', 'MANHATTAN'), ('queens', 'QUEENS'), ('bronx', 'BRONX'), ('brooklyn', 'BROOKLYN'), ('staten_island', 'STATEN ISLAND')], max_length=45, verbose_name='Boroughs Willing to Travel:'),
        ),
    ]
