# Generated by Django 3.2.7 on 2021-11-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_alter_profile_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='littleLeagueBaseball',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='littleLeagueSoftball',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tBall',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youthFootball',
        ),
        migrations.AlterField(
            model_name='profile',
            name='adultBaseball',
            field=models.BooleanField(default=False, verbose_name='Baseball'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adultFootball',
            field=models.BooleanField(default=False, verbose_name='Football'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adultSoftball',
            field=models.BooleanField(default=False, verbose_name='Softball'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='basketball',
            field=models.BooleanField(default=False, verbose_name='Basketball'),
        ),
    ]
